"""add musicbrainz_id and external_id

Revision ID: 7882722251d5
Revises: 7de5dd9958d4
Create Date: 2026-08-17 17:38:36.953426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7882722251d5'
down_revision: Union[str, None] = '7de5dd9958d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musicbrainz_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_music_requests_musicbrainz_id'), ['musicbrainz_id'], unique=False)

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musicbrainz_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_tracks_musicbrainz_id'), ['musicbrainz_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_musicbrainz_id'))
        batch_op.drop_column('musicbrainz_id')

    with op.batch_alter_table('music_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_requests_musicbrainz_id'))
        batch_op.drop_column('external_id')
        batch_op.drop_column('musicbrainz_id')

    # ### end Alembic commands ###
